# Generated by Django 3.1.2 on 2020-10-11 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('waiting', 'waiting'), ('ready', 'ready')], default='waiting', max_length=20),
        ),
    ]
