# Generated by Django 3.1.2 on 2020-10-11 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_ingredient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='order',
            field=models.ManyToManyField(related_name='order', to='orders.Order'),
        ),
    ]
